name: matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node node node-version
        run: node -v
      - name: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log node version
        run: node -v